# Generated by Django 4.2.5 on 2024-04-08 11:21

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='prod_img',
            field=models.ImageField(default=0, upload_to='productimages'),
        ),
        migrations.AddField(
            model_name='product',
            name='prod_img2',
            field=models.ImageField(default=0, upload_to='productimages'),
        ),
        migrations.AddField(
            model_name='product',
            name='prod_img3',
            field=models.ImageField(default=0, upload_to='productimages'),
        ),
        migrations.AddField(
            model_name='product',
            name='prod_outofstock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='prod_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
