# Generated by Django 4.2.5 on 2024-04-08 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_remove_product_price_product_prod_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prod_mrp',
            field=models.FloatField(default=0),
        ),
    ]
