# Generated by Django 4.2.5 on 2024-04-09 04:44

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_product_prod_mrp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Blog_name', models.CharField(max_length=100)),
                ('add_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('description', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
