# Generated by Django 4.2.5 on 2024-04-12 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0006_extendeduser'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_no', models.IntegerField(default=0)),
                ('customer_name', models.CharField(default=0, max_length=100)),
                ('customer_username', models.CharField(default=0, max_length=100)),
                ('phone', models.CharField(default=0, max_length=12)),
                ('email', models.CharField(default=0, max_length=100)),
                ('address', models.CharField(default=0, max_length=500)),
                ('Product_id', models.IntegerField(default=0)),
                ('product_img', models.ImageField(default=0, upload_to='productimages')),
                ('Product_quantity', models.IntegerField(default=1)),
                ('product_price', models.FloatField(default=0)),
                ('product_name', models.CharField(default=0, max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('add_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.extendeduser')),
                ('product_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.product')),
            ],
        ),
    ]
