# Generated by Django 4.2.5 on 2024-04-12 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0007_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_order_cost',
            field=models.FloatField(default=0),
        ),
    ]
