# Generated by Django 4.2.5 on 2024-04-12 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0008_order_total_order_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_order_cost',
            new_name='total_cost',
        ),
    ]
