# Generated by Django 4.2.5 on 2024-04-15 13:43

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0010_cancelation_policy_privacy_policy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='about_compeny',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
