# Generated by Django 4.2.5 on 2024-04-15 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0011_about_compeny'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_compeny',
            name='product_img',
            field=models.ImageField(default=0, upload_to='aboutusbanner'),
        ),
    ]
